### ISSUE TITLE
Use a non-copyleft license

### ISSUE THREAD

**Issue by sdvillal** [clarete/forbiddenfruit#12]
I read [here](https://news.ycombinator.com/item?id=5488148) forbiddenfruit was being relicensed to something like MIT, BSD, or at least LGPL. Is this still happening? I was planning to use it in a small [library of mine](https://github.com/sdvillal/whatami/blob/2b01e9423c657938ef62ae5481762d40710ff573/whatami/what.py#L856-L872), but I do not want to get GPL in the mix.

**Comment by clarete** [comment]
Does that help if I dual-license? I'll push a commit with the MIT file. Meanwhile, I give you express permission to link forbiddenfruit under the terms of the MIT license to your software.

I'd like keep GPL because I really agree on the reasons it exists, as well as consider it historically important for the free software. But it doesn't really have to bother anyone! :)

**Comment by sdvillal** [comment]
Yeah that will make it, thanks a lot! Would it then be possible to also update pypi?

**Comment by clarete** [comment]
I'll put it in the 0.1.3 patch

**Comment by clarete** [comment]
It's on master. New release will include. Sorry it took forever! :)
