### ISSUE TITLE
Some redefinitions blow up Python 

### ISSUE THREAD

**Issue by jonathaneunice** [clarete/forbiddenfruit#5]
Some redefinitions set the interpreter on fire. For example:

```
Python 2.7.2 (default, Oct 11 2012, 20:14:37)
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from forbiddenfruit import curse
>>> def notpop(self, key):
...     return self[key]
...
>>> curse(dict, 'pop', notpop)
>>> d = dict(a=1,b=2,c=3)
>>> d.pop('a')
Segmentation fault: 11
```

I had good results adding methods to `int` and `dict`, and adding or modifying methods in `str`. But my explorations in modifying existing `dict` methods all go **BOOM**.

This may be related to the `int` circumvention of cursed methods reported in [Issue #4](https://github.com/clarete/forbiddenfruit/issues/4), but the crash behavior is more severe and it could be caused by something else...so reporting separately.

**Comment by clarete** [comment]
Very old issue, the test above was actually flaky for years until #27 was merged a month ago. And although it was fixed, I replaced that test with something that doesn't suggest people that it might be a good idea to change `dict.pop`.

Also, this was one of the tickets that really made me think about not doing so much work on this project because I kinda realized that it will always be possible to crash python if this library is available. I still think it's a fun educational library but besides for testing purposes, I really think this is a weird idea to run any production code with this.
